# Generated by Django 4.1.2 on 2022-10-29 03:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0002_alter_artiste_first_name_alter_artiste_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiste',
            name='artiste_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_released', models.DateField()),
                ('likes', models.ManyToManyField(related_name='song', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
