# Generated by Django 4.1.2 on 2022-10-29 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0004_song_artiste_id_song_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='song', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('song_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_ids', to='musicapp.song')),
            ],
        ),
    ]
